[phases.setup]
nixPkgs = [
    "...",
    "ffmpeg",
    "fonts-dejavu-core",
    "nspr",
    "nss",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "pango",
    "cairo",
    "mesa",
    "expat",
    "fontconfig",
    "dbus",
    "glib",
    "gtk3",
    "libX11",
    "libXcomposite",
    "libXdamage",
    "libXext",
    "libXfixes",
    "libXrandr",
    "libgbm"
]

[phases.install]
cmds = ["npm install", "npx remotion browser ensure"]

[start]
cmd = "node server.js"
